services:
  api:
    image: api:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.api
    container_name: api
    restart: unless-stopped
    ports:
      - 28080:28080
    volumes:
      - ./repo-stat/api/config/config.yaml:/config.yaml
    environment:
      - LISTEN_ADDRESS=:28080
      - SUBSCRIBER_ADDRESS=subscriber:8080
      - PROCESSOR_ADDRESS=processor:8080
    depends_on:
      - subscriber
      - processor

  subscriber:
    image: subscriber:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.subscriber
    container_name: subscriber
    restart: unless-stopped
    ports:
      - 28081:8080
    volumes:
      - ./repo-stat/subscriber/config/config.yaml:/config.yaml
    environment:
      - LISTEN_ADDRESS=:8080
      - API_ADDRESS=api:8080

  processor:
    image: processor:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.processor
    container_name: processor
    restart: unless-stopped
    ports:
      - 28082:8080
    volumes:
      - ./repo-stat/processor/config/config.yaml:/config.yaml
    environment:
      - LISTEN_ADDRESS=:8080
      - COLLECTOR_ADDRESS=collector:8080
    depends_on:
      - collector

  collector:
    image: collector:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.collector
    container_name: collector
    restart: unless-stopped
    ports:
      - 28083:8080
    volumes:
      - ./repo-stat/collector/config/config.yaml:/config.yaml
    environment:
      - LISTEN_ADDRESS=:8080

  tests:
    image: tests:latest
    build:
      context: tests
    container_name: tests
    restart: "no"
    depends_on:
      - api
    network_mode: "service:api"