app:
  app_name: "repo-stat-subscriber"

grpc:
  address: "localhost:8080"
  timeout: "5s"

logger:
  log_level: "DEBUG"

database:
  dsn: "postgres://user:password@localhost:5432/repo_stat?sslmode=disable"